### ISSUE TITLE
Move CSVs to a folder

### ISSUE THREAD

**Issue by TheLime1** [TheLime1/TN_reddit_dataset#8]
so the huggingface push will be more efficient 
```yaml
name: Deploy to huggingface

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * 0" # Run every Sunday at midnight

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Filter CSV files
        run: |
          mkdir -p csv_files
          find . -name "*.csv" -exec cp {} csv_files/ \;
          
      - name: Change to csv_files directory
        run: cd csv_files

      - uses: backendcloud/hugging-push@v0.2.3
        with:
          # The Hugging Face repo id you want to sync to.
          huggingface_repo: "Tunisian_reddit"
          
          # Hugging Face token with write access
          hf_token: ${{ secrets.HF_TOKEN }}
          
          # Repository type
          repo_type: "dataset"
          
          # Set visibility
          private: false
          
          # Path to directory containing files to upload
          path: "./csv_files"
```
